services:

  database:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=supervision
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mariadata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - back_db

  backend:
    build: ./Backend
    restart: always
    environment:
      - DB_HOST=database       # nom du service DB
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=supervision
      - APP_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./Backend:/app
    networks:
      - front_back
      - back_db

  frontend:
    image: nginx:alpine
    restart: always
    volumes:
      - ./Frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - front_back

volumes:
  mariadata:

networks:
  front_back:
    driver: bridge
  back_db:
    driver: bridge
